VirtoCommerce.LiquidThemeEngine/Converters/ProductConverter.cs, VirtoCommerce.LiquidThemeEngine/Objects/Product.cs, VirtoCommerce.LiquidThemeEngine/Objects/Variant.cs, VirtoCommerce.Storefront.Model/Catalog/Product.cs, VirtoCommerce.Storefront.Model/Catalog/Services/IProductAvailabilityService.cs, VirtoCommerce.Storefront/Domain/Catalog/CatalogService.cs, VirtoCommerce.Storefront/Domain/Catalog/ProductAvailabilityService.cs
https://github.com/VirtoCommerce/vc-storefront/issues/53
=> extension for productAvailabilityService

.github/ISSUE_TEMPLATE.md, CONTRIBUTING.md, LICENSE, README.md
* Added badges to `README.md`
Due to GitHub recommendations:
* License moved to `LICENSE` file
* Added `CONTRIBUTING.md`
* Added `ISSUE_TEMPLATE.md`
=> Community-related changes

VirtoCommerce.Storefront/Controllers/AccountController.cs, VirtoCommerce.Storefront/Extensions/ClaimsPrincipalExtensions.cs
as github writed user name in  custom claims
=> Update create user

VirtoCommerce.Storefront.Model/Catalog/CategorySearchCriteria.cs, VirtoCommerce.Storefront.Model/Catalog/ProductSearchCriteria.cs, VirtoCommerce.Storefront/Domain/Catalog/CatalogConverter.cs
VirtoCommerce/vc-module-core#69
IMPORTANT: Need to update AutoRest clients before merging this PR. Otherwise build will fail because of missing field in search criteria.
=> Add fuzzy search support

VirtoCommerce.Storefront.Model/Common/Money/Currency.cs
=> Issue with decimals in pricing

VirtoCommerce.Storefront/Controllers/AccountController.cs
Not tested in default themes, sorry.
=> Added token validation to reset password & registration by invite forms

VirtoCommerce.Storefront.Model/Marketing/PromotionReward.cs, VirtoCommerce.Storefront.Tests/MarketingTests.cs, VirtoCommerce.Storefront/AutoRestClients/MarketingModuleApi.cs, VirtoCommerce.Storefront/Domain/Marketing/MarketingConverter.cs
using MaxLimit in MarketingConverter.ToPromotionReward
regenerated MarketingModuleApiI
=> Feature Limit the reward for relative discount

VirtoCommerce.LiquidThemeEngine/DotLiquidThemedView.cs
"version" parameter added to liquid context
=> "version" parameter added to liquid context

VirtoCommerce.Storefront/Domain/Catalog/CatalogConverter.cs
null value disables filtering by user groups
=> SearchCriteria.UserGroups should not be null if a customer has no user groups

VirtoCommerce.Storefront.Tests/Routing/RoutingTests.cs, VirtoCommerce.Storefront/Controllers/ErrorController.cs
Cause 404 code return instead of correct 4xx/5xx when other than GET http methods used for API request #168
=> Fixed routing in error controller

VirtoCommerce.LiquidThemeEngine/Converters/ProductConverter.cs, VirtoCommerce.LiquidThemeEngine/Objects/Product.cs
Created PR for Product SKU as instructed in https://github.com/VirtoCommerce/vc-storefront-core/issues/174
=> added Sku to Product liquid model

VirtoCommerce.Storefront.Model/Cart/UpdateCartCommentRequest.cs, VirtoCommerce.Storefront/Controllers/Api/ApiCartController.cs
Solve #180 issue, add request class for updateCartComment. As alternative solution we can change vc-theme-default and add quotes when call api method with one string parameter https://github.com/dvs39/vc-theme-default/commit/8ad97efaa2e644eccef146697d169c89de5d089c
=> Add request class for updateCartComment to pass comment to api

VirtoCommerce.Storefront.Model/Subscriptions/Subscription.cs
https://app.zenhub.com/workspaces/vc-operations-564a7a2e8294d8de6364f3d7/issues/virtocommerce/vc-storefront-core/109
=> #109 Fix for subscription interval value

VirtoCommerce.Storefront.Model/Customer/Contact.cs, VirtoCommerce.Storefront.Model/Security/OrganizationUserRegistration.cs, VirtoCommerce.Storefront.Model/Security/UserUpdateInfo.cs, VirtoCommerce.Storefront/Controllers/Api/ApiAccountController.cs
Add budget field to Contact, so if we decide to add new column in database we need to change only Budget property in Contact model
=> Add budget and it validation

VirtoCommerce.LiquidThemeEngine/Tags/FormTag.cs, VirtoCommerce.Storefront.Model/Common/Notifications/EmailNotificationBase.cs, VirtoCommerce.Storefront.Model/Common/Notifications/NotificationBase.cs, VirtoCommerce.Storefront.Model/Common/Notifications/SmsNotificationBase.cs, VirtoCommerce.Storefront.Model/Security/ForgotPassword.cs, VirtoCommerce.Storefront.Model/Security/ResetPassword.cs, VirtoCommerce.Storefront.Model/Security/ResetPasswordByCodeModel.cs, VirtoCommerce.Storefront/Controllers/AccountController.cs, VirtoCommerce.Storefront/Domain/Common/NotificationConverter.cs, VirtoCommerce.Storefront/Domain/Security/Notifications/EmailConfirmationNotification.cs, VirtoCommerce.Storefront/Domain/Security/Notifications/RegistrationInvitationNotification.cs, VirtoCommerce.Storefront/Domain/Security/Notifications/RemindUserNameNotification.cs, VirtoCommerce.Storefront/Domain/Security/Notifications/ResetPasswordEmailNotification.cs, VirtoCommerce.Storefront/Domain/Security/Notifications/ResetPasswordSmsNotification.cs, VirtoCommerce.Storefront/Infrastructure/StorefrontOptions.cs, VirtoCommerce.Storefront/appsettings.json
Added SMS confirmation for reset password
=> #212 SMS confirmation for reset password

VirtoCommerce.LiquidThemeEngine/Converters/CollectionConverter.cs
- Changed "manual" default sorting option to "priority-descending;name-ascending";
=> #248 "Featured" sorting is now working properly:

VirtoCommerce.Storefront/Domain/Cart/CartConverter.cs
Stored shopping cart of anonymous user has flag IsAnonymous = false
=> fixed ToShoppingCartDto method

VirtoCommerce.Storefront.Model/Cart/CartSearchCriteria.cs, VirtoCommerce.Storefront.Model/Customer/Organization.cs, VirtoCommerce.Storefront.Model/Pricing/PriceEvaluationContext.cs, VirtoCommerce.Storefront/Domain/Cart/CartBuilder.cs, VirtoCommerce.Storefront/Domain/Cart/CartService.cs, VirtoCommerce.Storefront/Domain/Customer/MemberService.cs, VirtoCommerce.Storefront/Domain/Inventory/InventoryService.cs
partial to classes
virtual to methods
change access modifier
small improvement for input data
=> Extensibility related changes requested

VirtoCommerce.Storefront.Model/Catalog/CategorySearchCriteria.cs, VirtoCommerce.Storefront.Model/Catalog/ProductSearchCriteria.cs
Sorry, I forgot to include these changes into PR #120. Without them you can't use this feature in theme.
=> Fuzzy search parameter parsing from query string added to catalog search criterias

VirtoCommerce.Storefront/Controllers/Api/ApiOrderController.cs, VirtoCommerce.Storefront/Domain/Security/CanAccessOrderAuthorizationHandler.cs, VirtoCommerce.Storefront/Startup.cs
If order not belong current user StorefrontException will be thrown.
=> user access checking was added into ApiOrderController.GetInvocePdf

VirtoCommerce.LiquidThemeEngine/VirtoCommerce.LiquidThemeEngine.csproj, VirtoCommerce.Storefront.Model/VirtoCommerce.Storefront.Model.csproj, VirtoCommerce.Storefront.Tests/VirtoCommerce.Storefront.Tests.csproj, VirtoCommerce.Storefront/Startup.cs, VirtoCommerce.Storefront/VirtoCommerce.Storefront.csproj
do not use Endpoint Routing logic
=> fix  CompatibilityVersion.Version_2_2 routing error

VirtoCommerce.Storefront/VirtoCommerce.Storefront.csproj
=> #259: upgraded Application Insights to 2.9.1.

VirtoCommerce.Storefront/Domain/WorkContextAccessor.cs
Eliminated static AsyncLocal<WorkContext> with usage of HttpContext.Items.
=> #263: Memory leaks

VirtoCommerce.Storefront/VirtoCommerce.Storefront.csproj, VirtoCommerce.Storefront/web.config
Adding support of 64 bit hosting for Azure
=> Added support 64 bit hosting for Azure

VirtoCommerce.LiquidThemeEngine/Filters/StandardFilters.cs
Added check of the format string for the ability to be a term for translation.
=> date filter is fixed

VirtoCommerce.Storefront.Model/Order/OrderSearchCriteria.cs, VirtoCommerce.Storefront.Model/Security/SecurityConstants.cs, VirtoCommerce.Storefront/Controllers/Api/ApiOrderController.cs, VirtoCommerce.Storefront/Domain/Customer/MemberConverter.cs, VirtoCommerce.Storefront/Domain/Order/OrderConverter.cs
New permission `sstorefront:order:view` was added.
New roles was added: **Procurement Portal Administrator** and **Procurement Porta; Agent**.
Organization convertation is extended. For phones and dynamic properties getting and saving.
OrderSearchCriteria was extended.
=> Necessary changes for the project

VirtoCommerce.Storefront/Controllers/Api/ApiOrderController.cs, VirtoCommerce.Storefront/Domain/Security/CanAccessOrderAuthorizationHandler.cs
Customer user can get any order if has next permission "storefront:order:view".
=> User can get any order

VirtoCommerce.Storefront/Domain/Catalog/CatalogWorkContextBuilderExtensions.cs
'Sort by' feature didn't work because sortBy is constantly being replaced by same value
fix for #314
=> fix sortBy prop assigning for productSearchcriteria

VirtoCommerce.Storefront/Domain/Cart/CartConverter.cs
=> Fix vp 1266 incorect tax with ava tax

VirtoCommerce.Storefront/Domain/Security/CustomCookieAuthenticationEvents.cs
Checked if store Uri is absolute and handled accordingly;
=> VP-1249: Fix building Uri for absolute redirect Uri

VirtoCommerce.Storefront/Controllers/BulkOrderController.cs
=> vp-1200 fix bulkOrder form can add to cart only one item

VirtoCommerce.Storefront/Controllers/AccountController.cs
=> vp-1079 fix Anti Forgery Token issue when reload login form.

VirtoCommerce.Storefront/Infrastructure/Autorest/ApiKeySecretAuthHandler.cs
Add user IP to requests header
=> VP-1423 send customerip to authorize.net

VirtoCommerce.Storefront/Domain/WorkContextBuilder.cs, VirtoCommerce.Storefront/Extensions/QueryCollectionExtensions.cs
Remove query escaping from StoreFront
=> Vp 1629 character escaping on search bar

VirtoCommerce.Storefront.Model/Security/User.cs, VirtoCommerce.Storefront/Controllers/Api/ApiCartController.cs, VirtoCommerce.Storefront/Domain/Marketing/MarketingConverter.cs, VirtoCommerce.Storefront/Domain/Order/Handlers/OrderEventsHandler.cs, VirtoCommerce.Storefront/Domain/Security/UserStoreStub.cs
Filled IsFirstTimeBuyer based on the user order existence;
Value is cached within the UserStoreStub and is reset after order creation;
=> VP-1637: Support IsFirstTimeBuyer promotion condition

VirtoCommerce.LiquidThemeEngine/Objects/Paginate.cs
=> VP-1644: Index Error on Pagination when Changing Page Size

VirtoCommerce.Storefront/Domain/Countries/FileSystemCountriesService.cs
=> VP-1257: Wrong value in country field

VirtoCommerce.Storefront/wwwroot/countries.json
Add missing Code2 and Code3
Fix wrong codes
=> VP-1742: Read iso country codes from our countries.json file

VirtoCommerce.Storefront/Controllers/Api/ApiListsController.cs
* ChangeListItem for changing quantity
* ClearList for removing all items from list
=> Add missing methods for working with lists

VirtoCommerce.Storefront/Domain/Cart/CartBuilder.cs
prevent sale price overwriting which leads to an incorrect totals calculation
=> VP-2120: Fix incorrect totals calculation

VirtoCommerce.Storefront.Model/Common/Money/Money.cs, VirtoCommerce.Storefront.Model/Marketing/PromotionReward.cs, VirtoCommerce.Storefront.Tests/Reward/PromotionRewardTest.cs
Get rid of double when work with money
=> VP-2194 Fix incorrect discount amount

VirtoCommerce.Storefront/Domain/Cart/CartBuilder.cs
Error when trying fetch payment plans on not existed cart
Prevent adding cart null id which fired exception
Check existence of cart id
=> VP-1947: Storefront - Auto order frequency resets when you go to the next stage of order creating

VirtoCommerce.Storefront.Model/Security/Specifications/IsUserLockedOutSpecification.cs, VirtoCommerce.Storefront.Model/Security/Specifications/IsUserSuspendedSpecification.cs, VirtoCommerce.Storefront/Controllers/AccountController.cs
Fixed regression caused by https://github.com/VirtoCommerce/vc-storefront-core/pull/409 - show proper errors based on the user state.
=> VP-2593: Fix login errors appearance

VirtoCommerce.Storefront.Tests/ShoppingCart/CartValidationTests.cs
Fix test after previous PR for ChangePriceItem validation
=> VP-2727: Fix test for ValidateChangePriceItem after last changes

VirtoCommerce.Storefront/Controllers/AccountController.cs
https://virtocommerce.atlassian.net/browse/VP-2274
=> VP-2274: Add null checking while displaying User Registration errors

.github/workflows/main.yml
CI fails on building docker image
Start using [this](https://github.com/VirtoCommerce/vc-docker/blob/master/linux/storefront/Dockerfile) dockerfile
Update path to the dockerfile
N/A
=> VP-2753: Update path to the dockerfile

.github/workflows/meds.yml
Added workflow which runs on push to meds/dev branch event and send an event to
VirtoCommerce/vc-meds-docker for rebuild meds-storefront docker image
=> VP-3169 Add workflow to build docker image

VirtoCommerce.LiquidThemeEngine/ShopifyLiquidThemeEngine.cs, VirtoCommerce.Storefront.Model/Features/FeaturesAgent.cs, VirtoCommerce.Storefront.Model/Features/IFeaturesAgent.cs, VirtoCommerce.Storefront.Tests/Features/FeaturesAgentTests.cs
This reverts commit 92077413ed4856837ff94a9f17442517ffa2349f.
=> Revert "get settings by correct way (#436)"

VirtoCommerce.Storefront.Model/Commands/MergeCartCommand.cs, VirtoCommerce.Storefront.Model/Contracts/MergeCartResponseDto.cs, VirtoCommerce.Storefront/Domain/Cart/ExperienceCartBuilder.cs, VirtoCommerce.Storefront/Infrastructure/QueryHelper.cs
=> Feature VP-2094: add merge cart

VirtoCommerce.Storefront.Model/Cart/Services/ICartBuilder.cs, VirtoCommerce.Storefront.Model/Commands/MergeCartCommand.cs, VirtoCommerce.Storefront.Model/Commands/RemoveCartCommand.cs, VirtoCommerce.Storefront/Controllers/Api/ApiListsController.cs, VirtoCommerce.Storefront/Domain/Cart/CartBuilder.cs, VirtoCommerce.Storefront/Domain/Cart/ExperienceCartBuilder.cs, VirtoCommerce.Storefront/Infrastructure/QueryHelper.cs
=> Feature VP-2094: Remove cart operation

VirtoCommerce.Storefront/Infrastructure/QueryHelper.cs
=> Fix VP-2094

VirtoCommerce.Storefront.Model/Cart/Services/ICartBuilder.cs, VirtoCommerce.Storefront.Model/Commands/ValidateCouponCommand.cs, VirtoCommerce.Storefront.Model/Contracts/ValidateCouponResponseDto.cs, VirtoCommerce.Storefront/Controllers/Api/ApiCartController.cs, VirtoCommerce.Storefront/Domain/Cart/CartBuilder.cs, VirtoCommerce.Storefront/Domain/Cart/ExperienceCartBuilder.cs, VirtoCommerce.Storefront/Infrastructure/QueryHelper.cs
=> Fix VP-2094: validate coupon implementation

VirtoCommerce.Storefront.Model/Quote/Services/IQuoteRequestBuilder.cs, VirtoCommerce.Storefront/Controllers/Api/ApiQuoteRequestController.cs, VirtoCommerce.Storefront/Domain/Quote/QuoteRequestBuilder.cs
=> VP-3540: Implement "Remove all quote items" functionality

VirtoCommerce.Storefront.Model/Contracts/ChangeCartItemCommentResponceDto.cs, VirtoCommerce.Storefront.Model/Contracts/RemoveCouponResponceDto.cs, VirtoCommerce.Storefront.Model/Contracts/RemoveShipmentResponceDto.cs, VirtoCommerce.Storefront.Model/Contracts/ShoppingCartDtoContainer.cs, VirtoCommerce.Storefront/Domain/Cart/ExperienceCartBuilder.cs
=> Fix VP-2094 fix types for responces

VirtoCommerce.Storefront.Model/Cart/ShoppingCart.cs, VirtoCommerce.Storefront/Domain/Cart/CartBuilder.cs
Also fixed  these  bugs VP-3337, VP-2455, VP-1886
=> VP-3336: Remove extra space from fluent validation ruleset value

VirtoCommerce.Storefront.IntegrationTests/Infrastructure/JTokenExtensions.cs, VirtoCommerce.Storefront.IntegrationTests/Infrastructure/TestEnvironment.cs, VirtoCommerce.Storefront.IntegrationTests/Tests/ApiCatalogControllerTests.cs
=> VP-3606: Add integration tests on catalog controllers in the storefront (API and with the views)

VirtoCommerce.Storefront/Controllers/Api/ApiCartController.cs
As a User, I want to update the quantity for multiple products, so I can improve UX for B2B scenarios.
A new API to update quantity for multiple lineitems.
=> VP-1219 Add API for bulk ChangeCartItemQty

VirtoCommerce.Storefront/Controllers/Api/ApiAccountController.cs
Empty organization was created after registration of personal account.
=> Fix Empty organization created after registration of personal account.

VirtoCommerce.Storefront/Controllers/Api/ApiAccountController.cs
We need to check if TFA is disabled before updating phoneNumber and set this new phoneNumber to unconfirmed
TFA scenarios:
1) TFA is disabled -> we can add/change  phoneNumber -> confirm it -> enable TFA
2) TFA is disabled -> enable TFA by adding new number and confirming it
=> VP-3686: Add checking for TFA,set phoneNumber to unconfirmed on update

VirtoCommerce.Storefront.Model/Catalog/Product.cs, VirtoCommerce.Storefront/Domain/Cart/CartConverter.cs, VirtoCommerce.Storefront/Domain/Catalog/CatalogConverter.cs, VirtoCommerce.Storefront/Extensions/OutlineExtensions.cs
=> VP-3895: Add outlines property to product for promotion evaluation

VirtoCommerce.Storefront.Model/Catalog/TermExtensions.cs, VirtoCommerce.Storefront/Domain/Catalog/CatalogConverter.cs, VirtoCommerce.Storefront/Domain/Catalog/GraphQlCatalogHelper.cs
Need to differ spaces in term name/values and term delimiters for proper parsing by search engine
=> VP-3940: Encode spaces in term strings

VirtoCommerce.Storefront.Model/Cart/ShoppingCart.cs, VirtoCommerce.Storefront/Domain/Cart/ExperienceCartBuilder.cs
Error when user add product to list
Fix GraphQL command
=> VP-3750: Fix error when user add product to list

VirtoCommerce.Storefront/Controllers/Api/ApiListsController.cs, VirtoCommerce.Storefront/Domain/Cart/ExperienceCartBuilder.cs
new wish list not showed in the list
Clear cache
=> VP-3733: fix cache issue when user create wishlist

VirtoCommerce.Storefront.Model/Contracts/DiscountDto.cs, VirtoCommerce.Storefront.Model/Contracts/ShoppingCartDto.cs, VirtoCommerce.Storefront/Domain/Order/OrderConverter.cs
https://virtocommerce.atlassian.net/browse/VP-4045
=> VP-4045 Fix: serialization for discounts

.github/workflows/main.yml
Build number always set to 1
fixed build number sequence (checkout fetch-depth parameter value set 1)
=> VP-4155: Fix build number count

VirtoCommerce.Storefront/Domain/Catalog/CatalogConverter.cs, VirtoCommerce.Storefront/Domain/Catalog/ExperienceCatalogService.cs, VirtoCommerce.Storefront/Domain/Catalog/GraphQlCatalogHelper.cs
https://virtocommerce.atlassian.net/browse/VP-4042
=> Fix VP-4042 translated props

VirtoCommerce.Storefront/Domain/Cart/CartConverter.cs
User see error when cart without any error
Check for null
=> VP-3968: Fix error parsing

VirtoCommerce.Storefront/Domain/Order/ExperienceCustomerOrderService.cs, VirtoCommerce.Storefront/Domain/Order/GraphQlOrderHelper.cs
Add UserId to order get/search requests to pass the current user
=> VP-3838: Add UserId to order get/search requests;

VirtoCommerce.Storefront/Domain/Cart/CartService.cs, VirtoCommerce.Storefront/Infrastructure/QueryHelper.cs
Paging is not working with wishlist 
use GraphQL paging
=> VP-4195: fix broken wishlist paging

VirtoCommerce.Storefront.Model/Security/SecurityConstants.cs, VirtoCommerce.Storefront.Model/WorkContext.cs, VirtoCommerce.Storefront/Middleware/WorkContextBuildMiddleware.cs
Also WorkContext was expanded with BusinessToBusinessRoles variable for VP-4108
=> VP-3930: Add a 'Purchasing Agent' role to the list of roles (for B2B store)

VirtoCommerce.Storefront/Controllers/Api/ApiAccountController.cs, VirtoCommerce.Storefront/Domain/Customer/ExperienceMemberService.cs, VirtoCommerce.Storefront/Domain/Customer/GraphQlMemberHelper.cs, VirtoCommerce.Storefront/Domain/Security/SecurityGraphQLProvider.cs
Absent security in XProfile 
Part of solution: Add userId to GraphQL command
=> VP-4133: x-profile xapi security

VirtoCommerce.Storefront/Controllers/AccountController.cs, VirtoCommerce.Storefront/Filters/AngularAntiforgeryCookieResultFilter.cs, VirtoCommerce.Storefront/Startup.cs
Manually set User in the HttpContext to avoid issues like the Antiforgery  cookies are  generated for an anonymous user within this request despite that fact what  user has signed in already
=> VP-1575 Fix 400 error when reset password

VirtoCommerce.Storefront/Controllers/Api/ApiOrderController.cs
=> VP-3949: Update order payment status and payment method

VirtoCommerce.Storefront.Model/Cart/PaymentMethod.cs, VirtoCommerce.Storefront/Domain/Stores/StoreService.cs
Previous changes are revetred, suggestion based on @tatarincev comment was implemented
=> VP-3949: Revert typeName change, add new field for displaying PM name

VirtoCommerce.Storefront.Model/Security/SecurityConstants.cs
We need to show all org users to every org member (https://virtocommerce.atlassian.net/browse/VP-3977)
=> VP-3977: Give permission to view org users to b2b roles

VirtoCommerce.Storefront/Controllers/AccountController.cs
Login on behalf doesn't work properly on B2B theme in http://webstore-platform.demo.govirto.com/B2B-store/
=> VP-4039: Fix Login on behalf for non-default stores

VirtoCommerce.Storefront/Controllers/AccountController.cs
If this option is set to `true`, we should not login on registration
=> VP-2342: Respect `IdentityOptions.SignIn.RequireConfirmedEmail` on registration

VirtoCommerce.Storefront.Model/Stores/Store.cs, VirtoCommerce.Storefront/Controllers/AccountController.cs, VirtoCommerce.Storefront/Domain/Stores/StoreConverter.cs
checking for store flag before sending a email verificaiton email
https://virtocommerce.atlassian.net/browse/VP-6885
=> VP-6885 add check for store Email verification enabled flag

VirtoCommerce.Storefront/Controllers/Api/ApiAccountController.cs
Set emailConfirmed to false if user change own email address
=> VP-6887: Set verified to false when changed email address in the existent account

VirtoCommerce.Storefront/Domain/Cart/CartConverter.cs
https://virtocommerce.atlassian.net/browse/PT-1095
=> PT-1095 set BillOfMaterials as physical product

VirtoCommerce.Storefront/Controllers/CommonController.cs
https://virtocommerce.atlassian.net/browse/PT-1214
=> PT-1216: Fix open redirect

VirtoCommerce.Storefront/Startup.cs
An equal PR to the platform:
https://github.com/VirtoCommerce/vc-platform/pull/2217
https://virtocommerce.atlassian.net/browse/PT-158
=> PT-1295: Configure ASP.NET Core to work on Linux and non-IIS reverse proxies

.github/pull_request_template.md, .github/workflows/main.yml
Description: 
--
QA-test: 
Demo-test: 
=> ST-13 Implement storefront CI.

VirtoCommerce.Storefront/Controllers/Api/ApiAccountController.cs
Description:
--
QA-test:
Demo-test:
Download artifact URL: ghcr.io/VirtoCommerce/storefront:6.0.0-pr-587-st-20-5f534834
=> ST-20: add logout endpoint to api

VirtoCommerce.Storefront/Domain/Stores/StoreService.cs, VirtoCommerce.Storefront/Infrastructure/StorefrontOptions.cs
https://virtocommerce.atlassian.net/browse/ST-371
Download artifact URL: ghcr.io/VirtoCommerce/storefront:6.0.0-pr-590-st-371-a18afe2e
=> ST-371: Add DefaultTheme option

VirtoCommerce.Storefront.Model/Security/ForgotPasswordModel.cs, VirtoCommerce.Storefront.Model/Security/ResetPasswordModel.cs, VirtoCommerce.Storefront.Model/Security/ValidateTokenModel.cs, VirtoCommerce.Storefront/Controllers/Api/ApiAccountController.cs
Description: 
--
QA-test: 
Demo-test: 
Download artifact URL: ghcr.io/VirtoCommerce/storefront:6.0.0-pr-592-st-155-forgot-password-api-8d45ef76
=> ST-155: implement API for the forgot password functionality

.deployment/storefront-app/argoDeploy.json, .github/workflows/deploy.yml, .github/workflows/main.yml, .github/workflows/pr-ci.yml, .github/workflows/pr-deploy.yml, .github/workflows/release-hotfix.yml, .github/workflows/release.yml
Description: 
QA delivery labels on the PR.
Dev delivery after successful dev branch update.
Demo delivery  after successful main (master) branch update.
Release workflow to releasing on demand.
Release-hotfix workflow to releasing hotfix on demand.
=> ST-1259: Implement automated deploy to Demo environment

VirtoCommerce.Storefront.Model/Language.cs, VirtoCommerce.Storefront.Model/SpaThemeContext.cs
Description: 
--
QA-test: 
Demo-test: 
=> feat: extend theme context with Lng and Currency data

VirtoCommerce.Storefront/Domain/Security/UserStoreStub.cs
Description: 
It is dependet to https://github.com/VirtoCommerce/vc-platform/pull/2496
--
QA-test:  ST-1879
Demo-test: 
=> fix(ST-1877): clean cache at user deleting in the admin UI

VirtoCommerce.LiquidThemeEngine/Filters/CommonFilters.cs
Description: 
--
QA-test: 
Demo-test: 
=> feat(ST-2061): implment the filter to get setting by key

VirtoCommerce.Storefront.Model/ISeoInfoService.cs, VirtoCommerce.Storefront.Model/SeoInfo.cs, VirtoCommerce.Storefront/Controllers/Api/ApiCommonController.cs, VirtoCommerce.Storefront/Domain/Common/SeoInfoConverter.cs, VirtoCommerce.Storefront/Domain/SeoInfoServise.cs, VirtoCommerce.Storefront/Startup.cs
Description: 
--
QA-test: 
Demo-test: 
=> feat(ST-2038): Implement an endpoint to get the seo info by the slug

VirtoCommerce.Storefront/Controllers/DesignerPreviewController.cs
Description: 
--
QA-test: 
Demo-test: 
=> rename json-preview view to preview

README.md
Description: 
Just fixed a single link as requested by Kristina Sinyugina.
--
QA-test: 
Demo-test: 
=> docs: Fix link

VirtoCommerce.Storefront.Model/Security/Login.cs, VirtoCommerce.Storefront.Model/Security/SecurityErrorDescriber.cs, VirtoCommerce.Storefront/Controllers/Api/ApiAccountController.cs
Description: 
--
QA-test: ST-2219
Demo-test: 
Download artifact URL: ghcr.io/virtocommerce/storefront:6.2.0-pr-612-st-2216-login-by-email-2775b65e
=> feat(ST-2216): sign in with email instead of username

VirtoCommerce.Storefront/Domain/StaticContent/PageBuilderContentLoader.cs
Description: 
there was an error when page had object in settings.
=> fix logic to read page metadata

VirtoCommerce.LiquidThemeEngine/ShopifyLiquidThemeEngine.cs, VirtoCommerce.Storefront.Model/StaticContent/IStaticContentService.cs, VirtoCommerce.Storefront/Controllers/Api/ApiCommonController.cs, VirtoCommerce.Storefront/Domain/StaticContent/StaticContentService.cs, VirtoCommerce.Storefront/Domain/StaticContent/StaticContentWorkContextBuilderExtensions.cs, VirtoCommerce.Storefront/Domain/WorkContextBuilder.cs
Description: 
--
QA-test: 
Demo-test: 
=> ignore cache in preview mode

VirtoCommerce.Storefront/Controllers/Api/ApiCommonController.cs
to get current version use endpoint /storefrontapi/version
Description: 
--
QA-test: 
Demo-test: 
=> feat: add ability to get storefront version

VirtoCommerce.Storefront/Infrastructure/Autorest/BaseAuthHandler.cs
Description: 
--
QA-test: 
Demo-test: 
=> fix: user request headers

VirtoCommerce.Storefront/Controllers/Api/ApiStaticContentController.cs
Description: 
--
QA-test: 
Demo-test: 
=> reset cache by content type

VirtoCommerce.Storefront/Controllers/DesignerPreviewController.cs
Description: 
--
QA-test: 
Demo-test: 
=> set correct model in preview block action

VirtoCommerce.Storefront.Model/Security/ConfirmEmailModel.cs, VirtoCommerce.Storefront/Controllers/Api/ApiAccountController.cs
Description: 
https://virtocommerce.atlassian.net/browse/ST-3430
--
QA-test: 
Demo-test: 
=> feat: add an email confirmation endpoint

VirtoCommerce.Storefront/Startup.cs
Description: 
--
QA-test: 
Demo-test: 
=> feat: enable Brotli response compression

VirtoCommerce.Storefront/Startup.cs
This reverts commit 6802c3d0f7ac41390132009fa020e04ca09f417b.
Description: 
--
QA-test: 
Demo-test: 
=> Revert "feat: enable Brotli response compression (#631)"

VirtoCommerce.Storefront/Controllers/Api/ApiThemeController.cs
Description: 
--
QA-test: 
Demo-test: 
=> fix: SPA theme context controller

VirtoCommerce.Storefront/AutoRestClients/PlatformModuleApi.cs, VirtoCommerce.Storefront/Domain/Security/CustomUserManager.cs
Description: 
https://virtocommerce.atlassian.net/browse/PT-9563
--
QA-test: 
Demo-test: 
=> PT-9563: use platform API for tokens

VirtoCommerce.Storefront/Controllers/Api/ApiCommonController.cs
Description: 
--
QA-test: 
Demo-test: 
=> feat: allow anonymous version request

VirtoCommerce.Storefront/Controllers/Api/ApiCommonController.cs, VirtoCommerce.Storefront/Controllers/Api/ApiThemeController.cs
Description: 
--
QA-test: 
Demo-test: 
=> PT-10944: return homepage for empty slug

VirtoCommerce.Storefront/Controllers/Api/ApiCommonController.cs
Description: 
--
QA-test: 
Demo-test: 
=> PT-11019: use full path to search page

VirtoCommerce.Storefront/Controllers/AccountController.cs
Description: 
fix: "return" used instead of "returnUrl" for Login on Behalf
--
QA-test: 
Demo-test: 
=> PT-12187: "return" used instead of "returnUrl" for Login on Behalf

VirtoCommerce.Storefront/Controllers/AssetController.cs
Description: 
- Add ability to range processing of video files
--
QA-test: 
Demo-test: 
=> Enable range processing in theme assets file result

VirtoCommerce.Storefront/Controllers/Api/ApiAccountController.cs
Description: 
https://virtocommerce.atlassian.net/browse/ST-4429
--
QA-test: 
Demo-test: 
=> feat: add API method to get password requirements

VirtoCommerce.Storefront/Domain/Security/SecurityConverter.cs
Description: 
--
QA-test: 
Demo-test: 
=> PT-12147: add PasswordExpired flag to user DTO converter

VirtoCommerce.Storefront.Model/Customer/Contact.cs, VirtoCommerce.Storefront/AutoRestClients/CustomerModuleApi.cs, VirtoCommerce.Storefront/Domain/Customer/MemberConverter.cs
Description: 
https://virtocommerce.atlassian.net/browse/PT-12676
--
QA-test: 
Demo-test: 
=> PT-12676: Add status to contact

VirtoCommerce.Storefront.Model/FormError.cs, VirtoCommerce.Storefront.Model/Security/SecurityErrorDescriber.cs, VirtoCommerce.Storefront/Controllers/Api/ApiAccountController.cs
Description: 
feat: PASSWORD_EXPIRED retrieves the UserId in order to facilitate the process of changing a user's password.
--
QA-test: 
Demo-test: 
=> PT-13537: Obtain User ID for Password Change

VirtoCommerce.Storefront.Model/Stores/Store.cs, VirtoCommerce.Storefront/Domain/Stores/StoreConverter.cs
Description: 
--
QA-test: 
Demo-test: 
=> PT-13757: read CreateAnonymousOrderEnabled store settings

VirtoCommerce.Storefront/Controllers/CommonController.cs, VirtoCommerce.Storefront/appsettings.json
Description: 
fix: If switching off the setting Allow anonymous users to visit the store, then the storefront requests many redirections
--
QA-test: 
Demo-test: 
=> PT-13906: too many redirection

VirtoCommerce.Storefront/Controllers/Api/ApiCommonController.cs
Description: 
https://virtocommerce.atlassian.net/browse/PT-13653
--
QA-test: 
Demo-test: 
=> PT-13653: ignore ContentFIle object from platform response

VirtoCommerce.Storefront/Controllers/AccountController.cs, VirtoCommerce.Storefront/Controllers/Api/ApiAccountController.cs
Description: 
fix: The attempt counter does not reset when logging in
--
QA-test: 
Demo-test: 
=> PT-14407: The attempt counter does not reset when logging in

.github/workflows/pr-ci.yml
Description: 
--
QA-test: 
Demo-test: 
=> Update PR CI

.github/workflows/main.yml, VirtoCommerce.Storefront/Domain/StaticContent/StaticContentWorkContextBuilderExtensions.cs
Description: 
--
QA-test: 
Demo-test: 
=> PT-14386: skip filter pages by language

.github/workflows/main.yml
Description: 
--
QA-test: 
Demo-test: 
=> Upgrade java & node.js

VirtoCommerce.Storefront/Infrastructure/Autorest/UserPasswordAuthHandler.cs, VirtoCommerce.Storefront/Startup.cs
Description: 
--
QA-test: 
Demo-test: 
=> VCST-115: add token connect proxy

VirtoCommerce.Storefront/Controllers/Api/ApiThemeController.cs
Description: 
--
QA-test: 
Demo-test: 
=> Mark replaced API obsolete

VirtoCommerce.Storefront/Infrastructure/Autorest/BaseAuthHandler.cs
Description: 
fix: An issue was identified where the anonymous cart was being reset upon browser refresh. Virto Storefront, Virto Commerce Experience and Profile Experience module should be updated as well.
--
QA-test: 
Demo-test: 
=> VCST-192: Anonymous Cart Reset Issue Upon Browser Refresh

.github/workflows/deploy.yml, .github/workflows/main.yml, .github/workflows/pr-ci.yml, .github/workflows/pr-deploy.yml, .github/workflows/release-branch.yml, .github/workflows/release.yml
Description: 
--
QA-test: 
Demo-test: 
=> #VCST-517: Use node 20

.github/workflows/deploy.yml
Description: 
--
QA-test: 
Demo-test: 
=> VCST-582: Update vc-build obsolete targets

VirtoCommerce.Storefront.Tests/VirtoCommerce.Storefront.Tests.csproj, VirtoCommerce.Storefront/VirtoCommerce.Storefront.csproj
https://virtocommerce.atlassian.net/browse/VCST-381
=> VCST-381: Update dependencies

VirtoCommerce.Storefront/Infrastructure/Autorest/UserPasswordAuthHandler.cs, VirtoCommerce.Storefront/Startup.cs
Description: 
--
QA-test: 
Demo-test: 
=> VCST-114: add proxy for /token endpoints

VirtoCommerce.Storefront/Infrastructure/Autorest/BaseAuthHandler.cs
Description: 
fix: Resolves the problem with login under personal account with IsAdministrator flag to virto storefront.
--
QA-test: 
Demo-test: 
=> VCST-905: Problem with login under personal account 

VirtoCommerce.Storefront/VirtoCommerce.Storefront.csproj
Description: 
fix: Critical CVE-2018-1000210
--
QA-test: 
Demo-test: 
=> VCST-914: Critical CVE-2018-1000210
