VirtoCommerce.LiquidThemeEngine/Converters/ProductConverter.cs
Before this fix, if product had variations, its availability was calculated using only these variations availability, but excluding product itself availability
Where exist first time: VirtoCommerce/vc-storefront@c97f735
When shouldn't pass quality gate after: VirtoCommerce/vc-storefront-core@f65b2a5
=> Fixed critical bug with product availability

VirtoCommerce.LiquidThemeEngine/Converters/ProductConverter.cs
* Reserved inventory quantity is not considered for InventoryQuantity in liquid
* Inventory policy should be "deny" following shopify rules if TrackInventory enabled (feature not used currently, only for Shopify compatibility)
=> Fixed inventory issues in liquid

VirtoCommerce.Storefront/Domain/Security/SecurityWorkContextBuilderExtensions.cs
When customers browse storefront anonymously, we login they as special ASP.NET user. And as usual user, anonymous may be logged out after specified period of inactivity. Also, if you will open login page, leave for some time and then enter credentials and try to login, you will get 400 error page because anitforgery token will be invalid (it still valid until cookie not expired). To prevent this, set the life time of anonymous user cookie to infinity (because DateTime has no such value, I use max possible value)
=> Do not logout anonymous user when cookie expire

README.md
In case someone's using the old vc-storefront's binaries, I've added the correct naming, because if he doesn't notice, he'll link to his old storefront.
=> Different name, changed every occurence of vc-storefront to vc-storefront-core.

VirtoCommerce.Storefront/Domain/Security/CustomCookieAuthenticationHandler.cs, VirtoCommerce.Storefront/Startup.cs
By default, ASP.NET Core do nothing after user cookie expiration. So:
* After cookie expiration customer may have bad UX: for example, they loose their cart
* If user was on page which require permissions, when they will be redirected to "Access denied" page
To prevent this, I want to redirect customer to login page when cookie expires.
=> Redirect to login when cookie expired

VirtoCommerce.Storefront.Tests/Routing/Infrastructure/RoutingDataResult.cs, VirtoCommerce.Storefront.Tests/Routing/Infrastructure/RoutingTestingActionFilter.cs, VirtoCommerce.Storefront.Tests/Routing/RoutingTests.cs
Changes made for #161:
* Added test cases described in #161.
* Reworked `POST` of test JSON data. Now it is translated from `UpperCamelCase` to `lowerCamelCase` to match JS naming convention and make tests more realistic.
* Reworked `POST` of test form data - now it doesn't ignore `objectToPost` passed to the method. It is not used at this moment, though - all methods that use `PostData` method are currently tested with empty data.
* Removed `RequestPath` and `Arguments` properties from `RoutingDataResult`. These properties seemed useful at the moment of `RoutingTestingActionFilter` creation, but tests did not make use of them. In fact, `Arguments` property broke tests of `AccountController.Register` and `AccountController.ConfirmInvitation` action routes:
1. Test code made HTTP request …
=> 161: added some routing tests

VirtoCommerce.Storefront.Model/Common/Money/Money.cs, VirtoCommerce.Storefront.Tests/Model/MoneyOperationTests.cs, VirtoCommerce.Storefront.Tests/ResponseCaching/ResponseCachingTests.cs
I recently noticed a strange behavior of the `Money.TruncatedAmount` property. According to the description, it should return the value of `InternalAmount` truncated by `DecimalDigits`, but it sometimes doesn't do that. For example, if the `InternalAmount` is equal to `0.999` and `DecimalDigits` is equal to 2, I expect it to return `0.99`, but instead it returns `0.5`.
So, I've attempted to fix the `TruncatedAmount` property and add some tests for it. What do you think? Have I got the purpose of this property right?
=> Fix for Money.TruncatedAmount behavior

VirtoCommerce.LiquidThemeEngine/VirtoCommerce.LiquidThemeEngine.csproj, VirtoCommerce.Storefront.Model/VirtoCommerce.Storefront.Model.csproj, VirtoCommerce.Storefront.Tests/VirtoCommerce.Storefront.Tests.csproj, VirtoCommerce.Storefront/VirtoCommerce.Storefront.csproj, VirtoCommerce.Storefront/web.config
- Microsoft.AspNetCore.App to 2.2.1 (VirtoCommerce.LiquidThemeEngine, VirtoCommerce.Storefront, VirtoCommerce.Storefront.Model)
- Microsoft.AspNetCore.Http.Extensions to 2.2.0 (VirtoCommerce.Storefront)
- Microsoft.AspNetCore.Mvc.Testing to 2.2.0 (VirtoCommerce.Storefront.Tests)
- Set TargetLatestRuntimePatch to VirtoCommerce.Storefront.Model.csproj to avoid version error: https://docs.microsoft.com/en-us/dotnet/core/deploying/runtime-patch-selection
=> #205 Migrate Storefront to NET Core 2.2.1:

VirtoCommerce.Storefront.Model/Order/ProcessPaymentResult.cs, VirtoCommerce.Storefront/Controllers/Api/ApiCartController.cs, VirtoCommerce.Storefront/Controllers/Api/ApiOrderController.cs, VirtoCommerce.Storefront/Domain/Order/OrderConverter.cs, VirtoCommerce.Storefront/Domain/Order/OrderCreatedInfo.cs, VirtoCommerce.Storefront/Domain/Order/ProcessOrderPaymentResult.cs
**Warning:** this PR will cause breaking changes. We need to first check and fix if needed problems in our themes.
Currently some storefront APIs return AutoRest models directly without converting into storefront models. It may cause some discomfort especially when working with models generated by AutoRest or SwaggerCodegen in typescript.
Also, removal of AutoRest models will significantly reduce size of OpenAPI document and number of generated models:
| Parameter | Before | After |
| --- | --- | --- |
| Number of models | 159 | 106 |
| Size of docs.json | 167 KB | 120 KB |
=> Storefront APIs should return only storefront models and avoid returning of AutoRest auto-generated models

VirtoCommerce.Storefront.Model/Cart/LineItem.cs, VirtoCommerce.Storefront.Model/Cart/Shipment.cs, VirtoCommerce.Storefront.Model/Order/LineItem.cs, VirtoCommerce.Storefront.Model/Order/ProcessPaymentResult.cs, VirtoCommerce.Storefront.Model/Order/Shipment.cs, VirtoCommerce.Storefront.Model/SwaggerCustomSchemaIdAttribute.cs, VirtoCommerce.Storefront/Controllers/Api/ApiCartController.cs, VirtoCommerce.Storefront/Controllers/Api/ApiOrderController.cs, VirtoCommerce.Storefront/Domain/Order/OrderConverter.cs, VirtoCommerce.Storefront/Domain/Order/OrderCreatedInfo.cs, VirtoCommerce.Storefront/Domain/Order/ProcessOrderPaymentResult.cs, VirtoCommerce.Storefront/Startup.cs
Instead of using full qualified type names like `VirtoCommerce.Storefront.Model.Catalog.Product` we may want to use friendly names like just `Product` in swagger schema. Otherwise some generation tools like swagger codegen will generate very long not useful class names for models (it's by design) like `virtoCommerceStorefrontModelCatalogProduct`.
Note: this PR depend on #253
=> Generate friendly names storefront models in swagger

VirtoCommerce.Storefront/Domain/Catalog/CatalogService.cs
Moved Product properties out of cached Product for search, as it was done for getting by ids. Thus we make properties caching distributed, and e.g. Prices would be updated when needed, as they are loaded independently.
=> #266 UserGroups, CurrentPricelists should be part of cacheKey in SearchProductsAsync

VirtoCommerce.Storefront/VirtoCommerce.Storefront.csproj
Storefront v4 fails in Azure with 
> HTTP Error 500.30 - ANCM In-Process Start Failure
if you have **ASP.NET Core Logging Extensions 2.2.0** installed. This upgrade resolves the problem
=> Bump Microsoft.Extensions.Logging.AzureAppServices version to 2.2.5

VirtoCommerce.Storefront/Domain/Catalog/CatalogConverter.cs
Using `criteria.Currency` instead of `workContext.CurrentCurrency`.
=> Select pricelists with requested currency when searchig for products

VirtoCommerce.Storefront/DependencyInjection/ServiceCollectionExtension.cs
Turn Off Cookies. ARR Affinity Cookie was cached the global level on the first request and storefront worked with a single instance of the platform although you set up multiple instances of the platform.
=> Ignore ARR Affinity Cookie

VirtoCommerce.Storefront.Model/Catalog/Category.cs, VirtoCommerce.Storefront/Domain/Catalog/CatalogConverter.cs
Change the type of category.properties from IList to IMutablePageList. Eventually, we can use dot notation in liquid template like this '{{ collection.properties.bottomSection.value }} ' to getting property value.
=> Vp 1268 Make category properties available in liquid handlers.

VirtoCommerce.LiquidThemeEngine/ISassFileManager.cs, VirtoCommerce.LiquidThemeEngine/SassFileManager.cs, VirtoCommerce.LiquidThemeEngine/ShopifyLiquidThemeEngine.cs, VirtoCommerce.Storefront/DependencyInjection/ServiceCollectionExtension.cs
About workaround with directories. SASS/SCSS allow to make import like this:
```scss
@import 'mixins';
```
If you have both `mixins` folder and `mixins.scss`, compiler will throw an exception because it can't determine which one use.
=> Added support of @import directives in sass

VirtoCommerce.Storefront/AutoRestClients/!readme.txt
Sometimes, during generating autorest client of your module using Swagger, the error 'Could not read 'http://...' could appear.
To prevent this error you have to generate Swagger description as a json file at first. 
And then use it as -input parameter for generating autorest client
=> chore #CCIT-301: add troubleshooting info into !readme.txt 

VirtoCommerce.LiquidThemeEngine/LiquidThemeEngineOptions.cs, VirtoCommerce.LiquidThemeEngine/ShopifyLiquidThemeEngine.cs, VirtoCommerce.Storefront/appsettings.json
Fully backward-compatible: see changes in settings
Support merge between themes in different stores and themes in the same store
=> VP-1558: Merge settings between base and current themes

VirtoCommerce.Storefront.Tests/Inventory/InventoryTests.cs, VirtoCommerce.Storefront/Domain/Inventory/InventoryService.cs
If item do not have record for inventory in default ffc, other available inventories could be used for inventory checking;
=> VP-2011: Use available inventory if nothing in default ffc

VirtoCommerce.Storefront/Startup.cs
Operations has incorrect IDs in Open API schema. Caused by migration to Swashbuckle v5
https://github.com/domaindrivendev/Swashbuckle.AspNetCore#assign-explicit-operationids
Add call of CustomOperationIds
VP-2615
=> VP-2615: Fix incorrect operation IDs in Open API schema

VirtoCommerce.Storefront.Model/Cart/Validators/ChangeCartItemPriceValidator.cs
Fix for https://virtocommerce.atlassian.net/browse/VP-2727
=> VP-2727: Fix error on adding same item with 0 price

.github/workflows/main.yml
When PR merged into dev tag look like `ver.5.0.0-SHA` adds to commit and shows in releases page.
Disable commit tagging in main.yml workflow
`Publish` job step  `name: Add tag "ver.${{ steps.image.outputs.tag }}"` in main.yml workflow deleted
=> VP-3624: Disable commit tagging in main.yml workflow

VirtoCommerce.Storefront.Model/Catalog/Product.cs, VirtoCommerce.Storefront/Domain/Cart/CartConverter.cs, VirtoCommerce.Storefront/Domain/Catalog/CatalogConverter.cs, VirtoCommerce.Storefront/Extensions/OutlineExtensions.cs
Marketing promotions don’t work as expected, because the wrong one outline for product is chosen.
In DynamicExpressionsModule we have support for multiple outlines, so just need to pass string that contains multiple outlines with separator 
Add new Product propetry - Outlines, that contains all outlines of product with separator and then pass it to ProductPromoEntry
=> VP-3582: Add outlines property to product for promotion evaluation

.github/workflows/main.yml
Storefront image tags generate in old format `version-sha`
Use `VirtoCommerce/vc-github-actions/get-image-version@dev` action
Added path-ignore for push and PR events
Added CI workflow manual run
Added version number as output for `build-package` job
Renamed `unit-test` job to `sonar-analyze`
Used the latest VirtoCommerce.GlobalTool version
=> VP-4155: Use Get image version action

VirtoCommerce.Storefront.Model/Catalog/Specifications/ProductIsAvailableSpecification.cs, VirtoCommerce.Storefront.Model/Catalog/Specifications/ProductIsInStockSpecification.cs
Can not by product when inventory preorder quantity is null
convert null to 0
=> FIX Can not by product when inventory preorder quantity is null

VirtoCommerce.Storefront/Filters/AngularAntiforgeryCookieResultFilter.cs
Starting from 84 version Chrome doesn't support cookies with SameSite=None without Secure flag
Use Lax mode or always use HTTPS and set Secure flag
Use Lax mode for CSRF token
=> VP-4168: Use Lax same site mode for XSRF-TOKEN cookie

VirtoCommerce.Storefront/VirtoCommerce.Storefront.csproj
This resolves the problem with absolute URI building on the Unix systems.
=> VP-4420: Update storefront VirtoCommerce.Tools dependency to latest v3.4

VirtoCommerce.Storefront.Model/Stores/Store.cs, VirtoCommerce.Storefront/Extensions/PathStringExtensions.cs, VirtoCommerce.Storefront/Infrastructure/StorefrontUrlBuilder.cs
On a Unix system Uri.TryCreate() behavior is not the same as on windows. It may cause problems. Therefore we need to check that scheme is not 'file' at absolute URI creating. 
https://github.com/dotnet/runtime/issues/22718
=> VP-4415 Add additional checking of scheme into places with Uri.TryCreate() for absolute URI creating. 

VirtoCommerce.Storefront/Domain/Stores/StoreService.cs
Fix for VP-3949: We need to show payment method name instead of typeName
=> VP-3949: Return payment method name instead of typeName

VirtoCommerce.Storefront/Domain/Stores/SelectCurrentStorePolicy.cs, VirtoCommerce.Storefront/Domain/Stores/StoreWorkContextBuilderExtensions.cs
There is no way to preview any other theme besides active.
Theme should be able to preview using query string **?previewtheme=**
Add query string interceptor and replace theme name by passed from **previewtheme** parameter.
=> VP-2076: Preview of theme always open active theme

VirtoCommerce.LiquidThemeEngine/Filters/UrlFilters.cs
Use aggregation field instead of label when building term url
When building the term url, the label of an aggregation is used instead of the name.
=> Use aggregation field instead of label

VirtoCommerce.LiquidThemeEngine/ThemeEngineCacheRegion.cs, VirtoCommerce.Storefront.Model/Common/Caching/CacheCancellableTokensRegistry.cs, VirtoCommerce.Storefront.Model/Common/Caching/CancellableCacheRegion.cs, VirtoCommerce.Storefront.Model/Common/Caching/GlobalCacheRegion.cs, VirtoCommerce.Storefront.Model/Common/Caching/TokenCancelledEventArgs.cs, VirtoCommerce.Storefront/Caching/Redis/RedisCachingMessage.cs, VirtoCommerce.Storefront/Caching/Redis/RedisStorefrontMemoryCache.cs, VirtoCommerce.Storefront/Domain/Cart/CartCacheRegion.cs, VirtoCommerce.Storefront/Domain/Customer/CutomerCacheRegion.cs, VirtoCommerce.Storefront/Domain/Inventory/InventoryCacheRegion.cs, VirtoCommerce.Storefront/Domain/Quote/QuoteCacheRegion.cs, VirtoCommerce.Storefront/Domain/Recommendations/RecommendationsCacheRegion.cs, VirtoCommerce.Storefront/Domain/Security/SecurityCacheRegion.cs, VirtoCommerce.Storefront/Domain/StaticContent/StaticContentCacheRegion.cs, VirtoCommerce.Storefront/Domain/Subscriptions/PaymentPlanCacheRegion.cs, VirtoCommerce.Storefront/Domain/Subscriptions/SubscriptionCacheRegion.cs, VirtoCommerce.Storefront/Domain/Tax/TaxCacheRegion.cs, VirtoCommerce.Storefront/Routing/RoutingCacheRegion.cs
Cache invalidation should be propagated to the Redis backplane to all instances, no matter if the instance got invalidation message contains record with that key or not.
Similar to the platform commits:
https://github.com/VirtoCommerce/vc-platform/commit/61aea3790c5beb19b2bf9f0eeeffc1bbeff962f4#diff-390f6702ff1f2d8cf904c1cb7570efb4
https://github.com/VirtoCommerce/vc-platform/commit/bbb8c318dfb6b6de8869bc4372ac403629512a00
=> VP-5527: Propagate cancellation token messages to backplane

VirtoCommerce.Storefront/Controllers/AccountController.cs
**Problem**
User confirmation took the user based on the currently logged in user, which is incorrect. User should be passed as a method parameter to allow not logged in user to confirm their emails.
**Solution**
Use passed userId to find the user for the email confirmation.
=> VP-2342: Rework ConfirmEmail method to get passed user instead of the current one

README.md, VirtoCommerce.Storefront/Startup.cs
To forward the scheme from the proxy in non-IIS scenarios, set `ASPNETCORE_FORWARDEDHEADERS_ENABLED` environment variable to `true`.
See docs for info.
https://devblogs.microsoft.com/aspnet/forwarded-headers-middleware-updates-in-net-core-3-0-preview-6/
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-5.0
=> VDS-241: Use Forwarded Headers Middleware to forward the scheme for Linux and non-IIS reverse proxies

VirtoCommerce.Storefront.Model/Common/ValueObject.cs, VirtoCommerce.Storefront.Tests/ValueObjectTests.cs
This PR fixes the following issues that lead to incorrect equality components and duplicate cache keys:
1. `null` and `"null"` values are considered equal.
2. Empty collections are just ignored.
=> ValueObjects with different values should not be equal and should have different cache keys

VirtoCommerce.Storefront/Startup.cs
When the same ApplicationDiscriminator used in Storefront and Platform, the Identity UserManager can validate tokens issued in both applications
=> VP-6894: Define ApplicationDiscriminator

.deployment/storefront-app/argoDeploy.json, .github/workflows/deploy.yml, .github/workflows/main.yml
Added deployment workflow (deploy.yml):
In the main workflow:
- removed "Set up JDK 11 for dotnet-sonarscanner" step as outdated
- added steps for push build Info to Jira
- added job for dev environment deployment; job runs on pus for dev branch or when the workflow runs manually
Added ArgoCD deployment config '.deployment/storefront-app/argoDeploy.json'
=> ST-7: Add storefront deploying workflow

.github/workflows/pr-ci.yml, VirtoCommerce.LiquidThemeEngine/ShopifyLiquidThemeEngine.cs, VirtoCommerce.LiquidThemeEngine/VirtoCommerce.LiquidThemeEngine.csproj, VirtoCommerce.Storefront.Model/VirtoCommerce.Storefront.Model.csproj, VirtoCommerce.Storefront.Tests/LiquidThemeEngine/ShopifyLiquidThemeEngineTests.cs, VirtoCommerce.Storefront.Tests/VirtoCommerce.Storefront.Tests.csproj, VirtoCommerce.Storefront/Startup.cs, VirtoCommerce.Storefront/VirtoCommerce.Storefront.csproj
Description: 
Closes ST-1218. Migrating vc-storefront to .NET6, upgrading dependencies.
--
QA-test: ST-1954
Demo-test: ST-1955
Download artifact URL: ghcr.io/virtocommerce/storefront:6.0.0-pr-602-dotnet-6-migration-5d6ae016
=> ST-1812: Storefront migration to .NET 6

VirtoCommerce.Storefront.Model/ISeoInfoService.cs, VirtoCommerce.Storefront.Model/SlugInfoResult.cs, VirtoCommerce.Storefront/Controllers/Api/ApiCommonController.cs, VirtoCommerce.Storefront/Domain/SeoInfoServise.cs, VirtoCommerce.Storefront/Extensions/SeoExtensions.cs
Description: 
--
QA-test: ST-2697
Demo-test: 
Download artifact URL: ghcr.io/virtocommerce/storefront:6.3.0-pr-613-st-2696-slug-endpoint-1a47611d
=> feat(ST-2696): implement the endpoint to get seoInfo for objects or static content by slug

Directory.Build.props, VirtoCommerce.Storefront.sln, VirtoCommerce.Storefront/Controllers/Api/ApiStaticContentController.cs, VirtoCommerce.Storefront/Infrastructure/Autorest/BaseAuthHandler.cs, VirtoCommerce.Storefront/Models/ResetCacheModel.cs, VirtoCommerce.Storefront/VirtoCommerce.Storefront.csproj
Description: 
--
QA-test: 
Demo-test: 
=> change approach to reset cache

VirtoCommerce.LiquidThemeEngine/Filters/HtmlFilters.cs, VirtoCommerce.LiquidThemeEngine/ShopifyLiquidThemeEngine.cs, VirtoCommerce.LiquidThemeEngine/VirtoCommerce.LiquidThemeEngine.csproj, VirtoCommerce.Storefront.Model/WorkContext.cs, VirtoCommerce.Storefront.Tests/VirtoCommerce.Storefront.Tests.csproj
Description: 
--
QA-test: 
Demo-test: 
=> feat: update Scriban, WorkContext and liquid html filters

VirtoCommerce.Storefront.Model/Security/Specifications/IsUserLockedByRequiredEmailVerificationSpecification.cs, VirtoCommerce.Storefront/Controllers/Api/ApiAccountController.cs
Description: 
fix: An blocked user received the error code email_verification_is_required. Extend IsUserLockedByRequiredEmailVerificationSpecification with Store Setting checking. email_verification_is_required returns if 
```cs
_user.Contact.Status == "Locked"
&& !_user.EmailConfirmed
&& store.Settings.GetSettingValue<bool>("Stores.EmailVerificationEnabled", false)
&& store.Settings.GetSettingValue<bool>("Stores.EmailVerificationRequired", false)
```
--
QA-test: 
Demo-test: 
=> PT-13384: An blocked user received the error code email_verification_is_required

VirtoCommerce.Storefront/Startup.cs
Description:
https://virtocommerce.atlassian.net/browse/VCST-473
* Adds proxy for XAPI subscription WebSocket connections same way as for other XAPI HTTP requests.
* Respect secure and insecure schemas (`http` -> `ws`, `https` -> `wss`)
* Sets default keep alive interval to 50 seconds (XAPI has 45 and it must be XAPI < storefront < theme)
--
QA-test: 
Demo-test: 
=> VCST-206: Proxy XAPI subscription websocket connections

.github/workflows/main.yml, .github/workflows/pr-ci.yml, .github/workflows/pr-deploy.yml, .github/workflows/release-branch.yml, Directory.Build.props, README.md, VirtoCommerce.LiquidThemeEngine/Exceptions/SaasCompileException.cs, VirtoCommerce.LiquidThemeEngine/VirtoCommerce.LiquidThemeEngine.csproj, VirtoCommerce.Storefront.Model/Common/Exceptions/StorefrontException.cs, VirtoCommerce.Storefront.Model/Features/Exceptions/FeaturesException.cs, VirtoCommerce.Storefront.Model/VirtoCommerce.Storefront.Model.csproj, VirtoCommerce.Storefront.Tests/VirtoCommerce.Storefront.Tests.csproj, VirtoCommerce.Storefront/Caching/Redis/RedisStorefrontMemoryCache.cs, VirtoCommerce.Storefront/Domain/Security/SecurityConverter.cs, VirtoCommerce.Storefront/Infrastructure/Exceptions/NoStoresException.cs, VirtoCommerce.Storefront/Infrastructure/Exceptions/NoThemeException.cs, VirtoCommerce.Storefront/Middleware/WorkContextBuildMiddleware.cs, VirtoCommerce.Storefront/Startup.cs, VirtoCommerce.Storefront/VirtoCommerce.Storefront.csproj, azuredeploy.json
Description: 
feat: Update vc-storefront to NET8
--
Download artifact URL: 
docker pull ghcr.io/virtocommerce/storefront:8.0.0-alpha.1048-vcst-631-net8-82e3dd8d
=> VCST-631: Update vc-storefront to NET8
